# Generated by Django 6.0.4 on 2026-05-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='description',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title',
        ),
    ]
